name: Build C++ on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build executable
        # Use MSVC's cl.exe compiler via Developer Command Prompt
        shell: powershell
        run: |
          # Setup MSVC environment (should be pre-installed on windows-latest runner)
          cmd /c "vcvarsall.bat x64 && cl /EHsc main.cpp /Fe:main.exe"

      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: cpp-windows-executable
          path: hellodocker.exe
