name: Build C++ on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup VS Dev environment and build
        shell: cmd
        run: |
          REM Call VS Developer Command Prompt to set env vars
          call "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=amd64

          REM Verify cl is found
          where cl

          REM Build your cpp code
          cl /EHsc main.cpp /Fe:main.exe

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp-windows-executable
          path: helldocker.exe

