name: Build C++ on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup MSBuild (includes MSVC compiler environment)
      - name: Setup MSBuild environment
        uses: microsoft/setup-msbuild@v1.1

      # Step 3: Compile your C++ code using cl.exe
      - name: Build with cl.exe
        shell: cmd
        run: cl /EHsc main.cpp /Fe:main.exe

      # Step 4: Upload the built executable as an artifact
      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp-windows-executable
          path: helldocker.exe

