name: Build C++ on Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build executable using MSVC
        shell: cmd
        run: |
          set "PF86=C:\Progra~2"
          for /f "usebackq tokens=*" %%i in (`"%PF86%\Microsoft Visual Studio\Installer\vswhere.exe" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath`) do set VSINSTALLDIR=%%i
          echo VSINSTALLDIR is %VSINSTALLDIR%
          call "%VSINSTALLDIR%\VC\Auxiliary\Build\vcvarsall.bat" x64
          cl /EHsc main.cpp /Fe:main.exe

      - uses: actions/upload-artifact@v4
        with:
          name: cpp-windows-executable
          path: helldocker.exe

