name: Build C++ on Linux

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build C++ executable
        run: g++ main.cpp -o hellodocker

      - name: List files
        run: ls -l

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_FOR_GHCR }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/hello-world-docker:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/hello-world-docker:latest

      - name: Run Docker Compose
        run: docker-compose up --build