name: Build C++ on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build executable
        shell: vs2022
        run: cl /EHsc main.cpp /Fe:main.exe

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: cpp-windows-executable
          path: hellodocker.exe
